version: "3.8"
services:
  vue:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
